"""
Visualize anomaly distortion metrics.

Produces five types of plots from the metrics CSV generated by
anomaly_distortion_metrics.py:

  1. Grouped bar chart   – mean ± std per metric, grouped by transformation
  2. Box / violin plots  – full distribution per metric and transformation
  3. Radar / spider chart – normalized metric profiles per transformation
  4. Correlation heatmap  – pairwise Pearson correlation between metrics
  5. Spatial heatmap overlay – per-pixel |diff|, Sobel, Laplacian on mammograms

Usage:
    python exploration/visualize_anomaly_metrics.py --config config/visualize_anomaly_metrics.yaml
"""

import argparse
from pathlib import Path

import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml


def load_config(config_path: str) -> dict:
    """Load configuration from YAML file."""
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# Metric grouping helpers
# ---------------------------------------------------------------------------

# Metrics that measure the *change* caused by the distortion (good for comparing transforms)
CHANGE_METRICS = [
    "pixel_mae",
    "pixel_rmse",
    "pixel_max_diff",
    "sobel_mae",
    "laplacian_mae",
    "border_intensity_step_manip",
    "border_pixel_mae_manip",
    "border_intensity_step_diff",
    "border_pixel_mae_diff",
]

# Integration quality metrics (higher is better for SSIM, lower for distance metrics)
QUALITY_METRICS = [
    "ssim",
    "histogram_dist",
    "local_contrast_diff",
]

# Short display labels for the change metrics
CHANGE_LABELS = {
    "pixel_mae": "Pixel MAE",
    "pixel_rmse": "Pixel RMSE",
    "pixel_max_diff": "Pixel Max diff",
    "sobel_mae": "Sobel MAE",
    "laplacian_mae": "Laplacian MAE",
    "border_intensity_step_manip": "Border int diff",
    "border_pixel_mae_manip": "Border pixel MAE",
    "border_intensity_step_diff": "Border int step Δ",
    "border_pixel_mae_diff": "Border pixel MAE Δ",
}

# Short display labels for quality metrics
QUALITY_LABELS = {
    "ssim": "SSIM",
    "histogram_dist": "Histogram distance",
    "local_contrast_diff": "Local contrast diff",
}


def _get_metric_cols(df: pd.DataFrame) -> list[str]:
    """Return all numeric metric column names."""
    skip = {"filename", "transformation"}
    return [c for c in df.columns if c not in skip and pd.api.types.is_numeric_dtype(df[c])]


def _has_groups(df: pd.DataFrame) -> bool:
    return "transformation" in df.columns and df["transformation"].nunique() > 1


# ---------------------------------------------------------------------------
# 1. Grouped bar chart
# ---------------------------------------------------------------------------


def plot_grouped_bar(df: pd.DataFrame, output_path: Path, figsize, dpi):
    """Mean ± std of change metrics, grouped by transformation."""
    cols = [c for c in CHANGE_METRICS if c in df.columns]
    labels = [CHANGE_LABELS.get(c, c) for c in cols]

    fig, ax = plt.subplots(figsize=figsize)

    if _has_groups(df):
        groups = sorted(df["transformation"].unique())
        n_groups = len(groups)
        x = np.arange(len(cols))
        width = 0.8 / n_groups

        for i, group in enumerate(groups):
            sub = df[df["transformation"] == group]
            means = [sub[c].mean() for c in cols]
            stds = [sub[c].std() for c in cols]
            # Asymmetric error bars: lower bound clipped at 0, upper extends normally
            lower_err = [max(0, m - s) for m, s in zip(means, stds)]
            upper_err = stds
            yerr = [np.array(lower_err), np.array(upper_err)]
            offset = (i - (n_groups - 1) / 2) * width
            ax.bar(x + offset, means, width, yerr=yerr, label=group, capsize=3)

        ax.legend()
    else:
        means = [df[c].mean() for c in cols]
        stds = [df[c].std() for c in cols]
        lower_err = [max(0, m - s) for m, s in zip(means, stds)]
        upper_err = stds
        yerr = [np.array(lower_err), np.array(upper_err)]
        ax.bar(range(len(cols)), means, yerr=yerr, capsize=3)

    ax.set_xticks(range(len(cols)))
    ax.set_xticklabels(labels)
    ax.set_ylabel("Value")
    ax.set_title(f"Masked Region Change (mean ± std by distortion method) [n={len(df)}]")
    plt.tight_layout()
    plt.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# 2. Box / violin plots
# ---------------------------------------------------------------------------


def plot_box_violin(df: pd.DataFrame, output_path_box: Path, output_path_violin: Path, figsize, dpi):
    """Create separate box and violin plots for change metrics, split by transformation."""
    cols = [c for c in CHANGE_METRICS if c in df.columns]
    labels = [CHANGE_LABELS.get(c, c) for c in cols]

    # Normalize each metric to [0, 1] so they share a y-axis
    normed = df[cols].copy()
    for c in cols:
        cmin, cmax = normed[c].min(), normed[c].max()
        normed[c] = (normed[c] - cmin) / (cmax - cmin + 1e-12)

    if _has_groups(df):
        normed["transformation"] = df["transformation"]

    # Box plot
    fig_box, ax_box = plt.subplots(figsize=figsize)

    if _has_groups(df):
        groups = sorted(df["transformation"].unique())
        colors = plt.cm.tab10.colors
        legend_handles = []

        spacing = len(groups) + 1
        for gi, group in enumerate(groups):
            sub = normed[normed["transformation"] == group][cols].values
            positions = [spacing * i + gi for i in range(len(cols))]
            bp = ax_box.boxplot(
                sub,
                positions=positions,
                widths=0.6,
                patch_artist=True,
                showfliers=False,
            )
            for patch in bp["boxes"]:
                patch.set_facecolor(colors[gi % len(colors)])
                patch.set_alpha(0.7)
            legend_handles.append(plt.Rectangle((0, 0), 1, 1, fc=colors[gi % len(colors)], alpha=0.7))

        ax_box.set_xticks([spacing * i + (len(groups) - 1) / 2 for i in range(len(cols))])
        ax_box.set_xticklabels(labels)
        ax_box.legend(legend_handles, groups)
    else:
        ax_box.boxplot(normed[cols].values, showfliers=False)
        ax_box.set_xticks(range(1, len(cols) + 1))
        ax_box.set_xticklabels(labels)

    ax_box.set_ylabel("Normalized value")
    ax_box.set_title(f"Masked Region Change Distribution (box plots by distortion method) [n={len(df)}]")
    plt.tight_layout()
    plt.savefig(output_path_box, dpi=dpi, bbox_inches="tight")
    plt.close(fig_box)

    # Violin plot
    fig_violin, ax_violin = plt.subplots(figsize=figsize)

    if _has_groups(df):
        for gi, group in enumerate(groups):
            sub = normed[normed["transformation"] == group][cols].values
            positions = [spacing * i + gi for i in range(len(cols))]
            parts = ax_violin.violinplot(
                sub,
                positions=positions,
                widths=0.6,
                showmeans=True,
                showmedians=False,
            )
            for pc in parts["bodies"]:
                pc.set_facecolor(colors[gi % len(colors)])
                pc.set_alpha(0.7)

        ax_violin.set_xticks([spacing * i + (len(groups) - 1) / 2 for i in range(len(cols))])
        ax_violin.set_xticklabels(labels)
        ax_violin.legend(legend_handles, groups)
    else:
        ax_violin.violinplot(normed[cols].values, showmeans=True, showmedians=False)
        ax_violin.set_xticks(range(1, len(cols) + 1))
        ax_violin.set_xticklabels(labels)

    ax_violin.set_ylabel("Normalized value")
    ax_violin.set_title(f"Masked Region Change Distribution (violin plots by distortion method) [n={len(df)}]")
    plt.tight_layout()
    plt.savefig(output_path_violin, dpi=dpi, bbox_inches="tight")
    plt.close(fig_violin)


# ---------------------------------------------------------------------------
# 3. Radar / spider chart
# ---------------------------------------------------------------------------


def plot_radar(df: pd.DataFrame, output_path: Path, figsize, dpi):
    """Radar chart of normalized metric means per transformation."""
    cols = [c for c in CHANGE_METRICS if c in df.columns]
    labels = [CHANGE_LABELS.get(c, c) for c in cols]
    n = len(cols)
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False).tolist()
    angles += angles[:1]

    fig, ax = plt.subplots(figsize=figsize, subplot_kw={"polar": True})

    # Normalize by global max per metric
    global_max = df[cols].max()

    if _has_groups(df):
        groups = sorted(df["transformation"].unique())
        for group in groups:
            sub = df[df["transformation"] == group]
            values = [(sub[c].mean() / (global_max[c] + 1e-12)) for c in cols]
            values += values[:1]
            ax.plot(angles, values, "o-", linewidth=2, label=group)
            ax.fill(angles, values, alpha=0.15)
    else:
        values = [(df[c].mean() / (global_max[c] + 1e-12)) for c in cols]
        values += values[:1]
        ax.plot(angles, values, "o-", linewidth=2, label="all")
        ax.fill(angles, values, alpha=0.15)

    ax.set_thetagrids(np.degrees(angles[:-1]), labels, size=8)
    ax.set_ylim(0, 1.1)
    ax.set_title(f"Masked Region Metric Profiles (normalized by distortion method) [n={len(df)}]", y=1.08)
    ax.legend(loc="upper right", bbox_to_anchor=(1.25, 1.1))
    plt.tight_layout()
    plt.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# 4. Correlation heatmap
# ---------------------------------------------------------------------------


def plot_correlation(df: pd.DataFrame, output_path: Path, figsize, dpi):
    """Pearson correlation heatmap of all numeric metrics."""
    cols = _get_metric_cols(df)
    corr = df[cols].corr()

    fig, ax = plt.subplots(figsize=figsize)
    im = ax.imshow(corr.values, cmap="RdBu_r", vmin=-1, vmax=1, aspect="auto")
    ax.set_xticks(range(len(cols)))
    ax.set_yticks(range(len(cols)))
    short = [CHANGE_LABELS.get(c, c.replace("_", "\n", 1)) for c in cols]
    ax.set_xticklabels(short, rotation=45, ha="right", fontsize=6)
    ax.set_yticklabels(short, fontsize=6)
    fig.colorbar(im, ax=ax, shrink=0.8, label="Pearson r")
    ax.set_title(f"Masked Region Metric Correlations [n={len(df)}]")
    plt.tight_layout()
    plt.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# 6. Quality metrics visualization
# ---------------------------------------------------------------------------


def plot_quality_bar(df: pd.DataFrame, output_path: Path, figsize, dpi):
    """Bar chart for integration quality metrics grouped by transformation."""
    cols = [c for c in QUALITY_METRICS if c in df.columns]
    labels = [QUALITY_LABELS.get(c, c) for c in cols]

    fig, ax = plt.subplots(figsize=figsize)

    if _has_groups(df):
        groups = sorted(df["transformation"].unique())
        n_groups = len(groups)
        x = np.arange(len(cols))
        width = 0.8 / n_groups

        for i, group in enumerate(groups):
            sub = df[df["transformation"] == group]
            means = [sub[c].mean() for c in cols]
            stds = [sub[c].std() for c in cols]
            lower_err = [max(0, m - s) for m, s in zip(means, stds)]
            upper_err = stds
            yerr = [np.array(lower_err), np.array(upper_err)]
            offset = (i - (n_groups - 1) / 2) * width
            ax.bar(x + offset, means, width, yerr=yerr, label=group, capsize=3)

        ax.legend()
    else:
        means = [df[c].mean() for c in cols]
        stds = [df[c].std() for c in cols]
        lower_err = [max(0, m - s) for m, s in zip(means, stds)]
        upper_err = stds
        yerr = [np.array(lower_err), np.array(upper_err)]
        ax.bar(range(len(cols)), means, yerr=yerr, capsize=3)

    ax.set_xticks(range(len(cols)))
    ax.set_xticklabels(labels)
    ax.set_ylabel("Value")
    ax.set_title(f"Integration Quality Metrics (mean ± std by distortion method) [n={len(df)}]")
    plt.tight_layout()
    plt.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def plot_quality_box_violin(df: pd.DataFrame, output_path_box: Path, output_path_violin: Path, figsize, dpi):
    """Box and violin plots for quality metrics, split by transformation."""
    cols = [c for c in QUALITY_METRICS if c in df.columns]
    if not cols:
        return
    
    labels = [QUALITY_LABELS.get(c, c) for c in cols]

    # Normalize each metric to [0, 1] so they share a y-axis
    normed = df[cols].copy()
    for c in cols:
        cmin, cmax = normed[c].min(), normed[c].max()
        normed[c] = (normed[c] - cmin) / (cmax - cmin + 1e-12)

    if _has_groups(df):
        normed["transformation"] = df["transformation"]

    # Box plot
    fig_box, ax_box = plt.subplots(figsize=figsize)
    legend_handles = []

    if _has_groups(df):
        groups = sorted(df["transformation"].unique())
        colors = plt.cm.tab10.colors

        spacing = len(groups) + 1
        for gi, group in enumerate(groups):
            sub_data = normed[normed["transformation"] == group][cols]
            positions = [spacing * i + gi for i in range(len(cols))]
            bp = ax_box.boxplot(
                [sub_data[c].values for c in cols],
                positions=positions,
                widths=0.6,
                patch_artist=True,
                showfliers=False,
            )
            for patch in bp["boxes"]:
                patch.set_facecolor(colors[gi % len(colors)])
                patch.set_alpha(0.7)
            legend_handles.append(plt.Rectangle((0, 0), 1, 1, fc=colors[gi % len(colors)], alpha=0.7))

        ax_box.set_xticks([spacing * i + (len(groups) - 1) / 2 for i in range(len(cols))])
        ax_box.set_xticklabels(labels)
        ax_box.legend(legend_handles, groups)
    else:
        ax_box.boxplot([normed[c].values for c in cols], showfliers=False)
        ax_box.set_xticks(range(1, len(cols) + 1))
        ax_box.set_xticklabels(labels)

    ax_box.set_ylabel("Normalized value")
    ax_box.set_title(f"Integration Quality Distribution (box plots by distortion method) [n={len(df)}]")
    plt.tight_layout()
    plt.savefig(output_path_box, dpi=dpi, bbox_inches="tight")
    plt.close(fig_box)

    # Violin plot
    fig_violin, ax_violin = plt.subplots(figsize=figsize)

    if _has_groups(df):
        for gi, group in enumerate(groups):
            sub_data = normed[normed["transformation"] == group][cols]
            positions = [spacing * i + gi for i in range(len(cols))]
            parts = ax_violin.violinplot(
                [sub_data[c].values for c in cols],
                positions=positions,
                widths=0.6,
                showmeans=True,
                showmedians=False,
            )
            for pc in parts["bodies"]:
                pc.set_facecolor(colors[gi % len(colors)])
                pc.set_alpha(0.7)

        ax_violin.set_xticks([spacing * i + (len(groups) - 1) / 2 for i in range(len(cols))])
        ax_violin.set_xticklabels(labels)
        ax_violin.legend(legend_handles, groups)
    else:
        ax_violin.violinplot([normed[c].values for c in cols], showmeans=True, showmedians=False)
        ax_violin.set_xticks(range(1, len(cols) + 1))
        ax_violin.set_xticklabels(labels)

    ax_violin.set_ylabel("Normalized value")
    ax_violin.set_title(f"Integration Quality Distribution (violin plots by distortion method) [n={len(df)}]")
    plt.tight_layout()
    plt.savefig(output_path_violin, dpi=dpi, bbox_inches="tight")
    plt.close(fig_violin)


def _load_image_triple(
    original_dir: Path,
    generated_dir: Path,
    row: pd.Series,
) -> tuple[np.ndarray, np.ndarray, np.ndarray] | None:
    """Load original, manipulated, and mask images for one metadata row."""
    filename = row["filename"]
    has_t = "transformation" in row.index and pd.notna(row.get("transformation"))

    if has_t:
        t = str(row["transformation"])
        manip_path = generated_dir / t / filename
        mask_path = generated_dir / t / "masks" / filename
    else:
        manip_path = generated_dir / filename
        mask_path = generated_dir / "masks" / filename

    orig_path = original_dir / filename

    for p in (orig_path, manip_path, mask_path):
        if not p.exists():
            return None

    orig = cv.imread(str(orig_path), cv.IMREAD_GRAYSCALE)
    manip = cv.imread(str(manip_path), cv.IMREAD_GRAYSCALE)
    mask = cv.imread(str(mask_path), cv.IMREAD_GRAYSCALE)
    if orig is None or manip is None or mask is None:
        return None

    _, mask = cv.threshold(mask, 127, 255, cv.THRESH_BINARY)
    return orig, manip, mask


def plot_spatial_heatmaps(
    rows: pd.DataFrame,
    original_dir: Path,
    generated_dir: Path,
    output_path: Path,
    figsize,
    dpi,
):
    """Unified spatial overlay for one image: one row per distortion method.

    Columns: Original | Generated | |Diff| | Sobel diff | Laplacian diff
    The crop region is derived from the first row's mask and shared across rows.
    """
    # Determine crop bounds from the first row's mask
    first_result = _load_image_triple(original_dir, generated_dir, rows.iloc[0])
    if first_result is None:
        return False
    _, _, mask_ref = first_result
    ys, xs = np.where(mask_ref > 0)
    pad = 30
    y1 = max(ys.min() - pad, 0)
    y2 = min(ys.max() + pad, mask_ref.shape[0])
    x1 = max(xs.min() - pad, 0)
    x2 = min(xs.max() + pad, mask_ref.shape[1])

    n_rows = len(rows)
    col_titles = ["Original", "Generated", "|Pixel Diff|", "Sobel diff", "Laplacian diff"]
    fig, axes = plt.subplots(n_rows, 5, figsize=(figsize[0], figsize[1] * n_rows))
    if n_rows == 1:
        axes = axes[np.newaxis, :]

    for ax, title in zip(axes[0], col_titles):
        ax.set_title(title, fontsize=10)

    for row_idx, (_, row) in enumerate(rows.iterrows()):
        result = _load_image_triple(original_dir, generated_dir, row)
        if result is None:
            for ax in axes[row_idx]:
                ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)
                for spine in ax.spines.values():
                    spine.set_visible(False)
            continue

        orig, manip, _ = result
        diff = np.abs(manip.astype(np.float64) - orig.astype(np.float64))
        sobel_orig = np.sqrt(cv.Sobel(orig, cv.CV_64F, 1, 0, ksize=3) ** 2 + cv.Sobel(orig, cv.CV_64F, 0, 1, ksize=3) ** 2)
        sobel_manip = np.sqrt(cv.Sobel(manip, cv.CV_64F, 1, 0, ksize=3) ** 2 + cv.Sobel(manip, cv.CV_64F, 0, 1, ksize=3) ** 2)
        lap_orig = cv.Laplacian(orig, cv.CV_64F, ksize=3)
        lap_manip = cv.Laplacian(manip, cv.CV_64F, ksize=3)

        panels = [
            orig[y1:y2, x1:x2],
            manip[y1:y2, x1:x2],
            diff[y1:y2, x1:x2],
            np.abs(sobel_manip - sobel_orig)[y1:y2, x1:x2],
            np.abs(lap_manip - lap_orig)[y1:y2, x1:x2],
        ]
        cmaps = ["gray", "gray", "inferno", "inferno", "inferno"]

        t_label = row.get("transformation", "")

        for col_idx, (ax, img, cmap) in enumerate(zip(axes[row_idx], panels, cmaps)):
            ax.imshow(img, cmap=cmap)
            ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)
            for spine in ax.spines.values():
                spine.set_visible(False)
            if col_idx == 0:
                ax.set_ylabel(t_label, fontsize=10, rotation=0, labelpad=50, va="center")

    fname = Path(rows.iloc[0]["filename"]).stem
    fig.suptitle(fname, fontsize=11)
    plt.tight_layout()
    plt.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return True


# ---------------------------------------------------------------------------
# 7. Parameter sweep visualisation
# ---------------------------------------------------------------------------


def plot_parameter_sweep(
    df: pd.DataFrame,
    output_dir: Path,
    figsize: tuple = (14, 6),
    dpi: int = 150,
):
    """Line charts showing metric means as a function of parameter value.

    Expects columns ``param_name`` and ``param_value`` (added by the pipeline).
    Produces one chart per transformation type (twirl / spherize).
    """
    if "param_name" not in df.columns or "param_value" not in df.columns:
        print("  Sweep visualisation skipped (no param_name/param_value columns)")
        return

    change_cols = [c for c in CHANGE_METRICS if c in df.columns]
    quality_cols = [c for c in QUALITY_METRICS if c in df.columns]

    for param_name, grp in df.groupby("param_name"):
        param_vals = sorted(grp["param_value"].unique())
        if len(param_vals) < 2:
            continue

        # --- Change metrics sweep ---
        if change_cols:
            fig, ax = plt.subplots(figsize=figsize)
            for col in change_cols:
                means = [grp[grp["param_value"] == v][col].mean() for v in param_vals]
                stds = [grp[grp["param_value"] == v][col].std() for v in param_vals]
                label = CHANGE_LABELS.get(col, col)
                ax.errorbar(param_vals, means, yerr=stds, marker="o", capsize=3, label=label)

            ax.set_xlabel(param_name.replace("_", " ").title())
            ax.set_ylabel("Metric value")
            n_per = len(grp) // len(param_vals)
            ax.set_title(f"Change Metrics vs {param_name.replace('_', ' ').title()} [n={n_per}/param]")
            ax.legend(fontsize=7, ncol=2)
            ax.set_xticks(param_vals)
            plt.tight_layout()
            path = output_dir / f"sweep_change_{param_name}.png"
            plt.savefig(path, dpi=dpi, bbox_inches="tight")
            plt.close(fig)
            print(f"  Sweep chart → {path}")

        # --- Quality metrics sweep ---
        if quality_cols:
            fig, ax = plt.subplots(figsize=figsize)
            for col in quality_cols:
                means = [grp[grp["param_value"] == v][col].mean() for v in param_vals]
                stds = [grp[grp["param_value"] == v][col].std() for v in param_vals]
                label = QUALITY_LABELS.get(col, col)
                ax.errorbar(param_vals, means, yerr=stds, marker="o", capsize=3, label=label)

            ax.set_xlabel(param_name.replace("_", " ").title())
            ax.set_ylabel("Metric value")
            n_per = len(grp) // len(param_vals)
            ax.set_title(f"Quality Metrics vs {param_name.replace('_', ' ').title()} [n={n_per}/param]")
            ax.legend(fontsize=7)
            ax.set_xticks(param_vals)
            plt.tight_layout()
            path = output_dir / f"sweep_quality_{param_name}.png"
            plt.savefig(path, dpi=dpi, bbox_inches="tight")
            plt.close(fig)
            print(f"  Sweep chart → {path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def visualize_all(config: dict):
    """Generate all visualization plots."""
    global CHANGE_METRICS, QUALITY_METRICS
    
    metrics_dir = Path(config["metrics_dir"])
    output_dir = Path(config["output_dir"])
    original_dir = Path(config.get("original_dir", ""))
    generated_dir = Path(config.get("generated_dir", ""))
    dpi = config.get("dpi", 150)
    num_spatial = config.get("num_spatial_samples", 3)

    # Update metric lists from config if provided
    if "visualize_change_metrics" in config and config["visualize_change_metrics"] is not None:
        CHANGE_METRICS = config["visualize_change_metrics"]
    if "visualize_quality_metrics" in config and config["visualize_quality_metrics"] is not None:
        QUALITY_METRICS = config["visualize_quality_metrics"]

    output_dir.mkdir(parents=True, exist_ok=True)

    metrics_csv = metrics_dir / "metrics.csv"
    if not metrics_csv.exists():
        print(f"metrics.csv not found in {metrics_dir}")
        return

    df = pd.read_csv(metrics_csv)
    print(f"Loaded {len(df)} rows from {metrics_csv}")

    # 1. Grouped bar chart
    path = output_dir / "bar_chart.png"
    plot_grouped_bar(df, path, tuple(config.get("figsize_bar", [14, 6])), dpi)
    print(f"  [1/5] Bar chart → {path}")

    # 2. Box / violin plots
    path_box = output_dir / "box_plots.png"
    path_violin = output_dir / "violin_plots.png"
    plot_box_violin(df, path_box, path_violin, tuple(config.get("figsize_box", [14, 6])), dpi)
    print(f"  [2/5] Box plots → {path_box}")
    print(f"  [2/5] Violin plots → {path_violin}")

    # 3. Radar chart
    path = output_dir / "radar_chart.png"
    plot_radar(df, path, tuple(config.get("figsize_radar", [8, 8])), dpi)
    print(f"  [3/5] Radar chart → {path}")

    # 4. Correlation heatmap
    path = output_dir / "correlation_heatmap.png"
    plot_correlation(df, path, tuple(config.get("figsize_heatmap", [10, 8])), dpi)
    print(f"  [4/5] Correlation heatmap → {path}")

    # 5. Spatial heatmap overlays
    if original_dir.exists() and generated_dir.exists():
        spatial_dir = output_dir / "spatial_heatmaps"
        spatial_dir.mkdir(exist_ok=True)

        # Sample images: pick the same filenames across all transformations
        if _has_groups(df):
            top_files = (
                df.groupby("filename")["pixel_mae"]
                .mean()
                .nlargest(num_spatial)
                .index
            )
            samples = df[df["filename"].isin(top_files)]
        else:
            samples = df.nlargest(num_spatial, "pixel_mae")

        count = 0
        for fname, file_rows in samples.groupby("filename"):
            stem = Path(fname).stem
            out_path = spatial_dir / f"{stem}.png"
            ok = plot_spatial_heatmaps(
                file_rows, original_dir, generated_dir, out_path,
                tuple(config.get("figsize_spatial", [16, 4])), dpi,
            )
            if ok:
                count += 1
                print(f"  [5/5] Spatial overlay → {out_path.name}")

        if count == 0:
            print("  [5/5] No spatial overlays generated (missing source images)")
    else:
        print("  [5/5] Skipped spatial overlays (original_dir / generated_dir not set)")

    # 6. Quality metrics
    path_quality_bar = output_dir / "quality_bar_chart.png"
    plot_quality_bar(df, path_quality_bar, tuple(config.get("figsize_bar", [14, 6])), dpi)
    print(f"  [6/8] Quality bar chart → {path_quality_bar}")

    path_quality_box = output_dir / "quality_box_plots.png"
    path_quality_violin = output_dir / "quality_violin_plots.png"
    plot_quality_box_violin(df, path_quality_box, path_quality_violin, tuple(config.get("figsize_box", [14, 6])), dpi)
    print(f"  [7/8] Quality box plots → {path_quality_box}")
    print(f"  [8/8] Quality violin plots → {path_quality_violin}")

    print(f"\nAll visualizations saved to: {output_dir}")


def main():
    parser = argparse.ArgumentParser(
        description="Visualize anomaly distortion metrics"
    )
    parser.add_argument(
        "--config", type=str, required=True,
        help="Path to YAML configuration file",
    )
    args = parser.parse_args()
    config = load_config(args.config)

    print("Configuration:")
    print("-" * 40)
    for k, v in config.items():
        print(f"  {k}: {v}")
    print("-" * 40)

    visualize_all(config)


if __name__ == "__main__":
    main()
